Error with migrating user model
probably had to do with previous migration not having a user model
https://stackoverflow.com/questions/42794212/migrating-from-django-user-model-to-a-custom-user-model
followed along this stackoverflow answer and resolved the problem